import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Navbar from "@/components/navbar";
import ProjectContextProvider from "@/context/project-context";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("RootLayout render");
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "hsl(263.4, 70%, 50.4%)",
        },
      }}
    >
      <html lang="en" style={{ height: "100%" }}>
        <body className={`${inter.className} h-full bg-background`}>
          <ThemeProvider>
            <ProjectContextProvider>
              <Navbar />
              {children}
            </ProjectContextProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
